name: On Push Main Branch
run-name: On Push to Main Branch

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'srcs/**'
      - 'tests/**'

permissions:
  contents: read

jobs:

  unit_test:
    uses: ./.github/workflows/sub_unit_tests.yml

  deploy_app:
    needs: unit_test
    uses: ./.github/workflows/sub_deploy.yml

  e2e_test:
    needs: deploy_app
    uses: ./.github/workflows/sub_e2e_tests.yml
