on:
  workflow_call:
  
permissions:
  contents: read

jobs:

  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.x
      - name: Trust HTTPS development certificate
        run: |
          export SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust:$SSL_CERT_DIR"
          dotnet dev-certs https --trust
      - name: Install ReportGenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Build Backend
        run: dotnet build datntdev.Microservice.slnf
      - name: Run unit tests for Solution
        run: dotnet test --no-build --settings .runsettings
      - name: Generate coverage report
        run: |
          reportgenerator \
          -reports:tests/**/coverage.cobertura.xml \
          -targetdir:tests/TestResults \
          -reporttypes:TextSummary \
          -assemblyfilters:"-*.Tests*"
          cat tests/TestResults/Summary.txt

  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: srcs/apps/Angular/package-lock.json
      - name: Install dependencies
        working-directory: srcs/apps/Angular
        run: npm install
      - name: Run unit tests
        working-directory: srcs/apps/Angular
        run: npm run test:ci
